### PR TITLE
WIP- svd generation script

### PR DESCRIPTION
**Pull request by jacobrosenthal**
this is a bit of yak shaving I was doing in my version that I kind of like.

I like the svd locally (assuming there is no licensing issues), or at least a link of where it was from so it can be traced. And I want the generation script/steps in there too. The way most people are doing it is a bash script which isnt portable. Also theyre using cargo to force install versions form and svd2rust and rustfm which means you cant/shouldnt really run it locally without polluting your local environemtn with who knows what, or in a container, which... fine. But I wanted to try to lock down the versions in a toml file instead. 

So Ive been working upstream on some issues and prs. Then I added an alias called gen so you call `cargo gen` or .. actually (and this is messier than I want sadly), `rm -rf src && mkdir src && touch src/lib.rs && cargo gen` and it'll regen the svd based on whatever versions are set in tools/Cargo.toml which I really like.

Some people have asked why not just make this a full crate, but I dont want to try to support the options of all the underlying tools, and the whole point of this is to pick different versions and patches of rustfmt, form, and svd2rust so a local script feels right.

thoughts?

sadly this doesnt work here presumably because of some of the workspace magic? But this works great in my repo. I wanted to see if you were even interested before I solved this to make it fit here
```
Jacobs-MacBook-Air:efm32hg309f64 jacobrosenthal$ rm -rf src && mkdir src && touch src/lib.rs && cargo gen
   Compiling scopeguard v0.3.3
   Compiling void v1.0.2
   Compiling lazy_static v1.2.0
   Compiling rand_core v0.3.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rand_core`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
 --> /Users/jacobrosenthal/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.2.0/src/inline_lazy.rs:9:1
  |
9 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `lazy_static`.
warning: build failed, waiting for other jobs to finish...
error: build failed

```

Also note, this probably shouldnt land until svd2rust patch lands and maybe form releases a new version as well

### CODE REVIEW

**Comment by fudanchii** [comment]
In short, yes, I'm expecting this to be in. 👍 

So I've been wondering about the structure of this workspace repo, as it was actually made like this to accommodate the initial development of the `hal` crate.

Though recently I started to prefer for the efm32 crate to be published on its own. But one thing that stopped me from publishing the crate is since it's actually generated from [rqou's efm32-unified-crate](https://github.com/rqou/efm32-unified-crate), and I think it's not for me to publish the generated result as I didn't even put the effort to obtain the svd.

> Some people have asked why not just make this a full crate, but I dont want to try to support the options of all the underlying tools, and the whole point of this is to pick different versions and patches of rustfmt, form, and svd2rust so a local script feels right.

I probably totally misunderstand this, but would you prefer to use efm32-rs instead? wondering what's the typical workflow for creating an app via tomu-hal, if, say, we're substituting `efm32hg309f64` with `efm32-rs`. I'm not sure since it seems like the device codes is expected to be generated manually with `cargo gen` first, wondering if the generated code is also expected to be distributed together with the svd later? (so it turns into a full crate)

Thank you for sharing this!

**Comment by jacobrosenthal** [comment]
>  not sure since it seems like the device codes is expected to be generated manually with cargo gen first, wondering if the generated code is also expected to be distributed together with the svd later? (so it turns into a full crate)
No, Im actually proposing to continue generating and shipping the peripheral access crate (pac, ie efm32hg309f64). Whether we ship the SVD is sort of inconsequential to me.. I just liked being very clear which we used in order to generate. also it makes it easier to run gen if the SVD is ready at hand.

This is more for us (and our developer users) to have a simple way to see versions we started from, patch them, track versions of tools we used cross platform, quickly try new rustfmt, svd2rust etc.

Yes I think separating the pac would help my error because it was working in my implementation. Im not too worried about if my crate or naming are used..

**Comment by jacobrosenthal** [comment]
So yeah just to show you it working if we refactor whether or not we use my pac repo check this out https://github.com/jacobrosenthal/imtomu-rs/tree/external_hal
this is hardcoded to use my generated bindings, seems to work


and likewise you should be able to grab that repo locally and gen new bindings
`cd efm32-rs && rm -rf src && mkdir src && touch src/lib.rs && cargo gen`

**Comment by jacobrosenthal** [comment]
Oh also, another plus to refactor out the workspace, Im trying to use intellij to check out their code completion, and it chokes on the current workspace style

**Comment by fudanchii** [comment]
I'm sold! :+1:

Let's point to the github repo for the time being, but hope you plan to release it to crates.io.

Let me change this :pray:

Thanks!

**Pull request closed without merging**
