### PR TITLE
deprecate led::LEDs in favor of led::Defaults

### PR DESCRIPTION
**Pull request by fudanchii**

### CODE REVIEW

**Comment by lucab** [comment]
Just curious, what's the rationale for this?
For reference, the `microbit` crate call its luminous peripherals `LED` and `Display`: https://github.com/therealprof/microbit/blob/c9298819b7e2bc816d25a07c49f6738bf2efbf56/src/led.rs

**Comment by fudanchii** [comment]
Thanks for taking a look at this. The rationale is subjective, and a short-sighted one here, was thinking that `led::LEDs` is redundant and isn't really distinguishable from the hypothetical user attached LED. Hence the `Defaults` naming.

e.g.

```rust
use led::LED;
use led::Defaults;

fn main() {
  // ...
  let def_leds = led::LEDs::new(gpio.pa0.into(), gpio.pb7.into());
  // // we don't implement 'new' yet for `led::LED` though
  let user_led = led::LED::new(gpio.pc0.into_pushpull());
 // ...
}
```

Above, I'd like to emphasize which leds are available by default, and I think it should be named as `Defaults` or `DefaultLEDs`. :thinking: 

But it's probably just me. I'm still reviewing this :pray:

**Comment by lucab** [comment]
Ah, that makes sense, thanks for the explanation. Maybe `BoardLEDs` then? (same approach could be used for the two on-board capacitive buttons later)

If you are re-thinking the whole thing, I also have a minor wishlist item which maybe could fit in here: can we make the constructor for on-board LEDs internally use the appropriate GPIO pins? That would be useful for casual tinkerers, who now have to lookup the led0<->pb7 connection somewhere.

**Comment by fudanchii** [comment]
> can we make the constructor for on-board LEDs internally use the appropriate GPIO pins? That would be useful for casual tinkerers, who now have to lookup the led0<->pb7 connection somewhere.

Indeed that's the approach we had before, but it's getting awkward as after the setup, we cannot use the rest of the GPIO peripheral since it's already splitted into pins, and some of the pins are moved to make the LEDs, so we cannot giving back the Pins struct.

With current structure all peripheral is owned by user app, so on board devices like LEDs need to be setup manually, so the used/moved pins, i.e. pa0 & pb7, effectively no longer usable but all other pins still available for another use.

Though I acknowledge with the current structure there's too much ceremony just to create a LED, so I think we can have some setup call that will automatically configure all the onboard devices without consuming the whole peripheral set later.

Probably introducing some method called, e.g. `tomu.configure_onboard_peripherals()` that will take all the required peripherals for LEDs, touch buttons, USB, then giving back another peripheral struct without all the used peripherals. :thinking:

**Comment by lucab** [comment]
> Probably introducing some method called, e.g. `tomu.configure_onboard_peripherals()` that will take all the required peripherals for LEDs, touch buttons, USB, then giving back another peripheral struct without all the used peripherals. :thinking:

Yes, that makes sense to me. At a top-level, I think you may want to have the following things (arbitrary naming, feel free to pick better ones):
 * a `BoardConfig{}` to specify which on-board peripherals to enable and expose a few popular knobs
 * a `BoardConfig::initialize(self) -> Result<(Board, X, Y, Z)>` to configure and initialize subsystems
 * a `Board{}` with several `Option<_>` fields, one for each on-board peripheral
 * several structs for individual peripherals and for the remaining free pins

**Comment by jacobrosenthal** [comment]
I think I like what Im doing over atsamd extending their existing pattern.

The BSP has a split() instead of take() function which returns a struct of peripheral structs, which just hold floating unconfigured pins. 
```
pub struct Buttons {
    pub latch: Pb0<Input<Floating>>,
    pub data_in: Pb30<Input<Floating>>,
    pub clock: Pb31<Input<Floating>>,
}
```
Then hide any setup in a function always called `init` (rather than new, because were separating creation from initializing on purpose)
```
impl Buttons {
    pub fn init(self, port: &mut Port) -> ButtonReader {
        let mut latch = self.latch.into_push_pull_output(port);
        latch.set_high().ok();
        let data_in = self.data_in.into_floating_input(port);
        let mut clock = self.clock.into_push_pull_output(port);
        clock.set_high().ok;

        ButtonReader {
            latch,
            data_in,
            clock,
            last: 0,
        }
    }
}
```
This way peripherals are never taken so rtfm etc still works fine, and also not EVERY peripheral gets inited inside the bsp, rather only what the example calls for.
```
let mut pins = hal::Pins::new(peripherals.PORT).split();
let mut buttons = pins.buttons.init(&mut pins.port);
```


If you already split in order to get some hal goodness, but still need a pin you can just dig it out of a peripheral struct without too much annoyance
```
let joy_x = pins.joystick.joy_x;
```

And of course a user could just not split, but still use one or more of the public structs 
```
    let mut buttons: hal::pins::ButtonReader = Buttons {
        latch: pins.button_latch,
        data_in: pins.button_out,
        clock: pins.button_clock,
    }
    .init(&mut pins.port);
```

Also, unrelated, I think catalina broke my ability to dfu my tomu. So thats why I'm not writing anything over here right now.

**Comment by fudanchii** [comment]
Changed how `Tomu` struct relate to `efm32hg::Peripherals` I think it covers what we discussed here 🙏🏾 , thank youu!

**Pull request closed without merging**
